Entity/AlbumEntity.php
<?php

/**
 * Copyright (c) KaikMedia.com 2015
 */

namespace Kaikmedia\GalleryModule\Entity;

use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\Common\Collections\ArrayCollection;
use Kaikmedia\GalleryModule\Entity\Base\AbstractBaseEntity;

/**
 * Media
 * @Gedmo\Tree(type="nested")
 * @ORM\Table(name="kmgallery_albums")
 * @ORM\Entity(repositoryClass="Kaikmedia\GalleryModule\Entity\Repository\AlbumsRepository")
 */
class AlbumEntity extends AbstractBaseEntity {

    /**
     * @Gedmo\TreeLeft
     * @ORM\Column(name="lft", type="integer")
     */
    private $lft;

    /**
     * @Gedmo\TreeLevel
     * @ORM\Column(name="lvl", type="integer")
     */
    private $lvl;

    /**
     * @Gedmo\TreeRight
     * @ORM\Column(name="rgt", type="integer")
     */
    private $rgt;

    /**
     * @Gedmo\TreeRoot
     * @ORM\Column(name="root", type="integer", nullable=true)
     */
    private $root;

    /**
     * @Gedmo\TreeParent
     * @ORM\ManyToOne(targetEntity="AlbumEntity", inversedBy="children")
     * @ORM\JoinColumn(name="parent", referencedColumnName="id", onDelete="CASCADE")
     */
    private $parent;

    /**
     * @ORM\OneToMany(targetEntity="AlbumEntity", mappedBy="parent")
     * @ORM\OrderBy({"lft" = "ASC"})
     */
    private $children;

    /**
     * categories
     *
     * @ORM\OneToMany(targetEntity="Kaikmedia\GalleryModule\Entity\AlbumCategoryEntity",
     *                mappedBy="entity", cascade={"remove", "persist"},
     *                orphanRemoval=true, fetch="EAGER")
     */
    private $category;

    /**
     * constructor
     */
    public function __construct() {
        parent::__construct();
        
        $this->category = new ArrayCollection();
    }

    /**
     * Set parent
     *
     * @return string
     */
    public function setParent(AlbumEntity $parent = null) {
        $this->parent = $parent;
    }

    /**
     * Get parent
     *
     * @return string
     */
    public function getParent() {
        return $this->parent;
    }

    /**
     * Get js tree array
     *
     * @return integer
     */
    public function getAsJsTreeArray() {
        $parent = $this->parent == null ? '#' : $this->parent->getId();
        $arrayTree = array('id' => $this->id,
            'text' => $this->getTitle(),
            'parent' => $parent
        );

        return $arrayTree;
    }

    public function getMedia() {
        $em = \ServiceUtil::getService('doctrine.entitymanager');
        $thisMedia = $em->getRepository('Kaikmedia\GalleryModule\Entity\MediaRelationsEntity')
                ->getAll(array('obj_name' => 'KaikmediaGalleryModule',
            'obj_id' => $this->id
        ));

        return $thisMedia;
    }

    public function __toString() {
        return $this->title;
    }
    
    /**
     * Get page category assignments
     *
     * @return \Doctrine\Common\Collections\ArrayCollection
     */
    public function getCategory() {
        return $this->category;
    }

    /**
     * Set page category assignments
     *
     * @param ArrayCollection $assignments
     */
    public function setCategory(ArrayCollection $assignments) {
        foreach ($this->category as $categoryAssignment) {
            if (false === $key = $this->collectionContains($assignments, $categoryAssignment)) {
                $this->category->removeElement($categoryAssignment);
            } else {
                $assignments->remove($key);
            }
        }
        foreach ($assignments as $assignment) {
            $this->category->add($assignment);
        }
    }    
}

Resources/views/Admin/mediaobjmap.html.twig
{% include "KaikmediaGalleryModule:Admin:header.html.twig" %}  
 {% form_theme form 'bootstrap_3_layout.html.twig' %}
    <h3><span class="fa fa-sitemap"></span>
        {{ __('Media to objects mappin')}}
    </h3>
<div class="container-fluid">
    <div class="row">
	<div class="list-group col-md-12">
		<div class="list-group-item col-md-12" style="background: #d9edf7;">
                {{ getstatusmsg() }}
                {{ form_start(form) }}
                {{ form_errors(form) }}                    
                <div class="col-md-2">
                {{ form_widget(form.name) }}                    
                </div>
                <div class="col-md-1 pull-right text-right">                
                {{ form_widget(form.filter, {'attr': {'class': 'btn btn-sm btn-info'}}) }}
                </div>
                {{ form_end(form) }} 
		</div>
		<div class="list-group-item col-md-12" style="background: #eee;">
    			<div class="col-md-3">{{ __('Obj name')}}</div>
    		    <div class="col-md-1">{{ __('Obj id')}}</div>
    		    <div class="col-md-2">{{ __('Media')}}</div>
    			<div class="col-md-2">{{ __('Created')}}</div>
    		    <div class="col-md-2">{{ __('Author')}}</div>
    			<div class="col-md-1 pull-right text-right">{{ __('Options')}}</div>
		</div>
		{%for mediaobject in mediaobjmap %}
		<div class="list-group-item col-md-12">
    			<div class="col-md-3">
    				<a href="{{ path('kaikmediagallerymodule_admin_mediastore', {'page': mediaobject.id}) }}">{{ mediaobject.obj_name }}</a>
    			</div>
    			<div class="col-md-1">
    				{{ mediaobject.obj_id }}
    			</div>			
    			<div class="col-md-2">
    			    {{ mediaobject.media.id }}	
    			</div>
    			<div class="col-md-2">
    				<p class="list-group-item-text">{{ mediaobject.createdAt|date('d/m/Y') }}</p>
    			</div>			
    			<div class="col-md-2">
    				<p class="list-group-item-text">{{ mediaobject.author.uname }}</p>
    			</div>			
    			<div class="col-md-2 text-right">
    				<a href="{{ path('kaikmediagallerymodule_admin_mediastore', {'page': mediaobject.id}) }}"><i
    					class="fa fa-pencil"></i></a>
    				<a data-toggle="collapse" data-target="#mediaobject-details-{{ mediaobject.id }}"  href="#" > <i class="fa fa-angle-down fa-1x" title="{{  __('Read') }}"> </i></a> 			
    			</div>   			
    			<div id="mediaobject-details-{{ mediaobject.id }}" class="row collapse">
                {% include "KaikmediaGalleryModule:Admin:file.details.html.twig" with {'file': mediaobject.media, 'settings': settings} %}  
                </div>   			
		</div>
        {% else %}
        <div class="list-group-item col-md-12">
        <p class="alert alert-warning text-center"> {{ __('No mappings found') }} </p>
        </div>
        {% endfor %}
		<div class="list-group-item col-md-12" style="background: #eee;">
			{% if maxPages > 1 %}
			<ul class="pagination pagination-sm">
				{# `«` arrow #}
				<li  {{ thisPage == 1 ? 'class="disabled"' }}><a
					href="{{ path('kaikmediagallerymodule_admin_mediastore', {page: thisPage-1 < 1 ? 1 : thisPage-1}) }}">«</a>
				</li> {# Render each page number #} {% for i in 1..maxPages %}
				<li  {{ thisPage == i ? 'class="active"' }}><a
					href="{{ path('kaikmediagallerymodule_admin_mediastore', {page: i}) }}">{{
						i }}</a></li> {% endfor %} {# `»` arrow #}
				<li  {{ thisPage == maxPages ? 'class="disabled"' }}><a
					href="{{ path('kaikmediagallerymodule_admin_mediastore', {page: thisPage+1 <= maxPages ? thisPage+1 : thisPage}) }}">»</a>
				</li>
			</ul>
			{% endif %}
		</div>
	</div>
	</div>
</div>
{% include "KaikmediaGalleryModule:Admin:footer.html.twig" %} 

Resources/views/Admin/settings.html.twig
{% extends 'KaikmediaGalleryModule:Base:admin.html.twig' %}
{% block header %}
    {% set settings={} %}
    {{ parent() }}
{% endblock %} 
{% block title %}
    {% set title_icon="<i class='fa fa-wrench'></i>" %}
    {% set title=__('Gallery settings and features') %}
    {{ parent() }}
{% endblock %}
{% block content %}
{% form_theme form with ['bootstrap_3_layout.html.twig',
    'ZikulaFormExtensionBundle:Form:bootstrap_3_zikula_admin_layout.html.twig',

    'KaikmediaGalleryModule:Form:radio.html.twig',
    'KaikmediaGalleryModule:Form:hooks.widget.html.twig',
    'KaikmediaGalleryModule:Form:providers.widget.html.twig',
    'KaikmediaGalleryModule:Form:subscribers.widget.html.twig',
    'KaikmediaGalleryModule:Form/Providers/MainMediaProvider:mainmedia.widget.html.twig',
    'KaikmediaGalleryModule:Form/Providers/GalleryProvider:gallery.widget.html.twig'

] %}

{#    'KaikmediaGalleryModule:Form/Providers/MediaProvider:media.widget.html.twig',#}
<div id="km_gallery_admin_settings">
    {{ showflashes() }}
    {{ form_start(form) }}
    {{ form_errors(form) }}
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#general" aria-controls="general" role="tab" data-toggle="tab">{{ __('General settings') }}</a></li>
        <li role="presentation"><a href="#hooks" aria-controls="hooks" role="tab" data-toggle="tab">{{ __('Hooks settings') }}</a></li>
    </ul>
    <div class="tab-content">
        <!-- General -->
        <div role="tabpanel" class="tab-pane active" id="general">
            <div class="col-md-12">
                <p class="col-md-12 help-block alert ">
                    {{ __("If the 'Gallery is accessible to visitors' setting is deactivated then only administrators will have access to the gallery. You can temporarily deactivate this setting to take the gallery off-line when you need to perform maintenance.")}}
                </p>
            </div>
            <fieldset>
                <legend>{{ __("General settings")}}</legend>
                <div class="form-group">
                    {{ form_label(form.gallery_enabled, __('Gallery is accesible to visitors') ,{ 'label_attr': {'class': 'col-md-4'} }) }}
                    <div class="col-md-8">
                        {{ form_widget(form.gallery_enabled, {'attr': {'class': 'btn btn-primary radio-inline' }}) }}
                        {{ form_errors(form.gallery_enabled) }}
                        <p class="col-md-12 help-block alert alert-info pull-right">
                        </p>
                    </div>
                </div>
                <div class="form-group">
                    {{ form_label(form.gallery_disabled_info, __('Message displayed if gallery is disabled'), { 'label_attr': {'class': 'col-md-4'} }) }}
                    <div class="col-md-8">
                        {{ form_widget(form.gallery_disabled_info, { 'attr': {'class': ''} }) }}
                        {{ form_errors(form.gallery_disabled_info) }}
                    </div>
                </div>
                <div class="form-group">
                    {{ form_label(form.upload_dir, __('Top Upload directory') ,{ 'label_attr': {'class': 'col-md-4'} }) }}
                    <div class="col-md-8">
                        {{ form_widget(form.upload_dir, {'attr': {'class': '' }}) }}
                        {{ form_errors(form.upload_dir) }}
                        <p class="col-md-12 help-block alert {% if is_writeable %}alert-success{% else %}alert-danger{% endif %} pull-right">
                        {% if is_writeable %}
                            <i class="fa fa-check-circle" aria-hidden="true"></i>
                        {% else %}
                            <i class="fa fa-exclamation-circle" aria-hidden="true"></i>
                        {% endif %}
                        {{ __('Directory:') }} {{ project_dir }}
                        {% if is_writeable %} {{ __('is writeable') }} {% else %} {{ __('is not writeable or does not exist') }}{% endif %}
                        </p>
                    </div>
                </div>
            </fieldset>
        </div>
        <!-- Hook -->
        <div role="tabpanel" class="tab-pane" id="hooks">
            <div class="col-md-12">
                <p class="col-md-12 help-block alert ">
                    {{ __("This is Dizkus hooks status it shows you current Dizkus hooks settings.")}}
                </p>
            </div>
            <div class="form-group">
                <div class="col-md-12">
                    {{ form_widget(form.hooks, { 'attr': {'class': ''} }) }}
                </div>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-offset-6 col-md-8">
            {{ form_widget(form.save, {'attr': {'class': 'btn btn-success'}}) }}
            {{ form_widget(form.restore, {'attr': {'class': 'btn btn-danger'}}) }}
        </div>
    </div>
    {{ form_end(form) }}
</div>
{% endblock %}